---
- name: remove the mariadb package
  become: yes
  yum: name=mariadb-libs state=absent

- name: install mysql57 el
  become: yes
  yum:
    name: http://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm
    state: present

- name: install mysql package
  yum: name="{{ packages }}"
  become: yes
  vars:
    packages:
      - mysql-community-server

- name: enable mysql service
  service: name=mysqld enabled=yes
  become: yes

- name: start mysql service
  service: name=mysqld state=started
  become: yes

- name: get mysql temporary root password
  become: yes
  shell: cat /var/log/mysqld.log | grep "temporary password" | awk '{print $11}'
  register: mysql_temp_root_password

- name: Install PyMysql
  shell: >
    pip install PyMySQL
  become: yes

- name: Check if root password is unset
  shell: >
    mysql -u root
    -proot
    -h localhost
    -e "quit"
  changed_when: false
  ignore_errors: true
  register: root_pwd_check

- debug: var=mysql_temp_root_password.stdout

- name: change password validation to the easy way
  shell: |
    mysql -u root -p'{{ mysql_temp_root_password.stdout }}' --connect-expired-password -e "SET GLOBAL validate_password_length=4;"
    mysql -u root -p'{{ mysql_temp_root_password.stdout }}' --connect-expired-password -e "SET GLOBAL validate_password_policy=LOW;"

- name: change root user password
  shell: |
    mysql -u root -p'{{ mysql_temp_root_password.stdout }}' --connect-expired-password -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';"
